/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Lei1RouteImport } from './routes/lei-1'
import { Route as Lei2RouteImport } from './routes/lei-2'
import { Route as Lei3RouteImport } from './routes/lei-3'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QuadroRouteImport } from './routes/quadro'
import { Route as QuestoesRouteImport } from './routes/questoes'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Lei1Route = Lei1RouteImport.update({
  id: '/lei-1',
  path: '/lei-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Lei2Route = Lei2RouteImport.update({
  id: '/lei-2',
  path: '/lei-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Lei3Route = Lei3RouteImport.update({
  id: '/lei-3',
  path: '/lei-3',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QuadroRoute = QuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesRoute = QuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/lei-1': typeof Lei1Route
  '/lei-2': typeof Lei2Route
  '/lei-3': typeof Lei3Route
  '/login': typeof LoginRoute
  '/quadro': typeof QuadroRoute
  '/questoes': typeof QuestoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/lei-1': typeof Lei1Route
  '/lei-2': typeof Lei2Route
  '/lei-3': typeof Lei3Route
  '/login': typeof LoginRoute
  '/quadro': typeof QuadroRoute
  '/questoes': typeof QuestoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anotacoes': typeof AnotacoesRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/dashboard': typeof DashboardRoute
  '/lei-1': typeof Lei1Route
  '/lei-2': typeof Lei2Route
  '/lei-3': typeof Lei3Route
  '/login': typeof LoginRoute
  '/quadro': typeof QuadroRoute
  '/questoes': typeof QuestoesRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anotacoes'
    | '/cadastro'
    | '/contato'
    | '/dashboard'
    | '/lei-1'
    | '/lei-2'
    | '/lei-3'
    | '/login'
    | '/quadro'
    | '/questoes'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anotacoes'
    | '/cadastro'
    | '/contato'
    | '/dashboard'
    | '/lei-1'
    | '/lei-2'
    | '/lei-3'
    | '/login'
    | '/quadro'
    | '/questoes'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/anotacoes'
    | '/cadastro'
    | '/contato'
    | '/dashboard'
    | '/lei-1'
    | '/lei-2'
    | '/lei-3'
    | '/login'
    | '/quadro'
    | '/questoes'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotacoesRoute: typeof AnotacoesRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  DashboardRoute: typeof DashboardRoute
  Lei1Route: typeof Lei1Route
  Lei2Route: typeof Lei2Route
  Lei3Route: typeof Lei3Route
  LoginRoute: typeof LoginRoute
  QuadroRoute: typeof QuadroRoute
  QuestoesRoute: typeof QuestoesRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lei-1': {
      id: '/lei-1'
      path: '/lei-1'
      fullPath: '/lei-1'
      preLoaderRoute: typeof Lei1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lei-2': {
      id: '/lei-2'
      path: '/lei-2'
      fullPath: '/lei-2'
      preLoaderRoute: typeof Lei2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lei-3': {
      id: '/lei-3'
      path: '/lei-3'
      fullPath: '/lei-3'
      preLoaderRoute: typeof Lei3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quadro': {
      id: '/quadro'
      path: '/quadro'
      fullPath: '/quadro'
      preLoaderRoute: typeof QuadroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes': {
      id: '/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof QuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotacoesRoute: AnotacoesRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  DashboardRoute: DashboardRoute,
  Lei1Route: Lei1Route,
  Lei2Route: Lei2Route,
  Lei3Route: Lei3Route,
  LoginRoute: LoginRoute,
  QuadroRoute: QuadroRoute,
  QuestoesRoute: QuestoesRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
